// Comprehensive global destinations dataset
// All countries + major cities worldwide with region tagging

export const DESTINATIONS = [
  // ============ EUROPE ============
  // Countries
  { name: 'France', country: 'France', type: 'country', region: 'europe' },
  { name: 'Italy', country: 'Italy', type: 'country', region: 'europe' },
  { name: 'Spain', country: 'Spain', type: 'country', region: 'europe' },
  { name: 'Germany', country: 'Germany', type: 'country', region: 'europe' },
  { name: 'United Kingdom', country: 'United Kingdom', type: 'country', region: 'europe' },
  { name: 'Portugal', country: 'Portugal', type: 'country', region: 'europe' },
  { name: 'Greece', country: 'Greece', type: 'country', region: 'europe' },
  { name: 'Netherlands', country: 'Netherlands', type: 'country', region: 'europe' },
  { name: 'Switzerland', country: 'Switzerland', type: 'country', region: 'europe' },
  { name: 'Austria', country: 'Austria', type: 'country', region: 'europe' },
  { name: 'Belgium', country: 'Belgium', type: 'country', region: 'europe' },
  { name: 'Czech Republic', country: 'Czech Republic', type: 'country', region: 'europe' },
  { name: 'Poland', country: 'Poland', type: 'country', region: 'europe' },
  { name: 'Sweden', country: 'Sweden', type: 'country', region: 'europe' },
  { name: 'Norway', country: 'Norway', type: 'country', region: 'europe' },
  { name: 'Denmark', country: 'Denmark', type: 'country', region: 'europe' },
  { name: 'Finland', country: 'Finland', type: 'country', region: 'europe' },
  { name: 'Ireland', country: 'Ireland', type: 'country', region: 'europe' },
  { name: 'Hungary', country: 'Hungary', type: 'country', region: 'europe' },
  { name: 'Croatia', country: 'Croatia', type: 'country', region: 'europe' },
  { name: 'Romania', country: 'Romania', type: 'country', region: 'europe' },
  { name: 'Iceland', country: 'Iceland', type: 'country', region: 'europe' },
  { name: 'Slovenia', country: 'Slovenia', type: 'country', region: 'europe' },
  { name: 'Montenegro', country: 'Montenegro', type: 'country', region: 'europe' },
  { name: 'Albania', country: 'Albania', type: 'country', region: 'europe' },
  { name: 'Serbia', country: 'Serbia', type: 'country', region: 'europe' },
  { name: 'Bosnia and Herzegovina', country: 'Bosnia and Herzegovina', type: 'country', region: 'europe' },
  { name: 'North Macedonia', country: 'North Macedonia', type: 'country', region: 'europe' },
  { name: 'Bulgaria', country: 'Bulgaria', type: 'country', region: 'europe' },
  { name: 'Slovakia', country: 'Slovakia', type: 'country', region: 'europe' },
  { name: 'Estonia', country: 'Estonia', type: 'country', region: 'europe' },
  { name: 'Latvia', country: 'Latvia', type: 'country', region: 'europe' },
  { name: 'Lithuania', country: 'Lithuania', type: 'country', region: 'europe' },
  { name: 'Malta', country: 'Malta', type: 'country', region: 'europe' },
  { name: 'Cyprus', country: 'Cyprus', type: 'country', region: 'europe' },
  { name: 'Luxembourg', country: 'Luxembourg', type: 'country', region: 'europe' },
  { name: 'Monaco', country: 'Monaco', type: 'country', region: 'europe' },
  // Cities
  { name: 'Paris, France', country: 'France', type: 'city', region: 'europe' },
  { name: 'Rome, Italy', country: 'Italy', type: 'city', region: 'europe' },
  { name: 'Florence, Italy', country: 'Italy', type: 'city', region: 'europe' },
  { name: 'Venice, Italy', country: 'Italy', type: 'city', region: 'europe' },
  { name: 'Milan, Italy', country: 'Italy', type: 'city', region: 'europe' },
  { name: 'Naples, Italy', country: 'Italy', type: 'city', region: 'europe' },
  { name: 'Amalfi Coast, Italy', country: 'Italy', type: 'city', region: 'europe' },
  { name: 'Barcelona, Spain', country: 'Spain', type: 'city', region: 'europe' },
  { name: 'Madrid, Spain', country: 'Spain', type: 'city', region: 'europe' },
  { name: 'Seville, Spain', country: 'Spain', type: 'city', region: 'europe' },
  { name: 'Valencia, Spain', country: 'Spain', type: 'city', region: 'europe' },
  { name: 'Malaga, Spain', country: 'Spain', type: 'city', region: 'europe' },
  { name: 'London, UK', country: 'United Kingdom', type: 'city', region: 'europe' },
  { name: 'Edinburgh, UK', country: 'United Kingdom', type: 'city', region: 'europe' },
  { name: 'Manchester, UK', country: 'United Kingdom', type: 'city', region: 'europe' },
  { name: 'Berlin, Germany', country: 'Germany', type: 'city', region: 'europe' },
  { name: 'Munich, Germany', country: 'Germany', type: 'city', region: 'europe' },
  { name: 'Hamburg, Germany', country: 'Germany', type: 'city', region: 'europe' },
  { name: 'Amsterdam, Netherlands', country: 'Netherlands', type: 'city', region: 'europe' },
  { name: 'Lisbon, Portugal', country: 'Portugal', type: 'city', region: 'europe' },
  { name: 'Porto, Portugal', country: 'Portugal', type: 'city', region: 'europe' },
  { name: 'Athens, Greece', country: 'Greece', type: 'city', region: 'europe' },
  { name: 'Santorini, Greece', country: 'Greece', type: 'city', region: 'europe' },
  { name: 'Mykonos, Greece', country: 'Greece', type: 'city', region: 'europe' },
  { name: 'Crete, Greece', country: 'Greece', type: 'city', region: 'europe' },
  { name: 'Prague, Czech Republic', country: 'Czech Republic', type: 'city', region: 'europe' },
  { name: 'Vienna, Austria', country: 'Austria', type: 'city', region: 'europe' },
  { name: 'Salzburg, Austria', country: 'Austria', type: 'city', region: 'europe' },
  { name: 'Zurich, Switzerland', country: 'Switzerland', type: 'city', region: 'europe' },
  { name: 'Geneva, Switzerland', country: 'Switzerland', type: 'city', region: 'europe' },
  { name: 'Interlaken, Switzerland', country: 'Switzerland', type: 'city', region: 'europe' },
  { name: 'Brussels, Belgium', country: 'Belgium', type: 'city', region: 'europe' },
  { name: 'Bruges, Belgium', country: 'Belgium', type: 'city', region: 'europe' },
  { name: 'Budapest, Hungary', country: 'Hungary', type: 'city', region: 'europe' },
  { name: 'Warsaw, Poland', country: 'Poland', type: 'city', region: 'europe' },
  { name: 'Krakow, Poland', country: 'Poland', type: 'city', region: 'europe' },
  { name: 'Stockholm, Sweden', country: 'Sweden', type: 'city', region: 'europe' },
  { name: 'Copenhagen, Denmark', country: 'Denmark', type: 'city', region: 'europe' },
  { name: 'Oslo, Norway', country: 'Norway', type: 'city', region: 'europe' },
  { name: 'Bergen, Norway', country: 'Norway', type: 'city', region: 'europe' },
  { name: 'Helsinki, Finland', country: 'Finland', type: 'city', region: 'europe' },
  { name: 'Dublin, Ireland', country: 'Ireland', type: 'city', region: 'europe' },
  { name: 'Reykjavik, Iceland', country: 'Iceland', type: 'city', region: 'europe' },
  { name: 'Dubrovnik, Croatia', country: 'Croatia', type: 'city', region: 'europe' },
  { name: 'Split, Croatia', country: 'Croatia', type: 'city', region: 'europe' },
  { name: 'Zagreb, Croatia', country: 'Croatia', type: 'city', region: 'europe' },
  { name: 'Ljubljana, Slovenia', country: 'Slovenia', type: 'city', region: 'europe' },
  { name: 'Bucharest, Romania', country: 'Romania', type: 'city', region: 'europe' },
  { name: 'Sofia, Bulgaria', country: 'Bulgaria', type: 'city', region: 'europe' },
  { name: 'Belgrade, Serbia', country: 'Serbia', type: 'city', region: 'europe' },
  { name: 'Tallinn, Estonia', country: 'Estonia', type: 'city', region: 'europe' },
  { name: 'Riga, Latvia', country: 'Latvia', type: 'city', region: 'europe' },
  { name: 'Vilnius, Lithuania', country: 'Lithuania', type: 'city', region: 'europe' },
  { name: 'Valletta, Malta', country: 'Malta', type: 'city', region: 'europe' },
  { name: 'Nice, France', country: 'France', type: 'city', region: 'europe' },
  { name: 'Lyon, France', country: 'France', type: 'city', region: 'europe' },
  { name: 'Marseille, France', country: 'France', type: 'city', region: 'europe' },
  { name: 'Kotor, Montenegro', country: 'Montenegro', type: 'city', region: 'europe' },
  { name: 'Tirana, Albania', country: 'Albania', type: 'city', region: 'europe' },
  { name: 'Bratislava, Slovakia', country: 'Slovakia', type: 'city', region: 'europe' },
  { name: 'Mostar, Bosnia and Herzegovina', country: 'Bosnia and Herzegovina', type: 'city', region: 'europe' },
  { name: 'Cinque Terre, Italy', country: 'Italy', type: 'city', region: 'europe' },

  // ============ NORTH AMERICA ============
  // Countries
  { name: 'United States', country: 'United States', type: 'country', region: 'north-america' },
  { name: 'Canada', country: 'Canada', type: 'country', region: 'north-america' },
  { name: 'Mexico', country: 'Mexico', type: 'country', region: 'north-america' },
  { name: 'Costa Rica', country: 'Costa Rica', type: 'country', region: 'north-america' },
  { name: 'Panama', country: 'Panama', type: 'country', region: 'north-america' },
  { name: 'Guatemala', country: 'Guatemala', type: 'country', region: 'north-america' },
  { name: 'Belize', country: 'Belize', type: 'country', region: 'north-america' },
  { name: 'Honduras', country: 'Honduras', type: 'country', region: 'north-america' },
  { name: 'El Salvador', country: 'El Salvador', type: 'country', region: 'north-america' },
  { name: 'Nicaragua', country: 'Nicaragua', type: 'country', region: 'north-america' },
  { name: 'Cuba', country: 'Cuba', type: 'country', region: 'north-america' },
  { name: 'Jamaica', country: 'Jamaica', type: 'country', region: 'north-america' },
  { name: 'Dominican Republic', country: 'Dominican Republic', type: 'country', region: 'north-america' },
  { name: 'Puerto Rico', country: 'Puerto Rico', type: 'country', region: 'north-america' },
  { name: 'Trinidad and Tobago', country: 'Trinidad and Tobago', type: 'country', region: 'north-america' },
  { name: 'Bahamas', country: 'Bahamas', type: 'country', region: 'north-america' },
  { name: 'Barbados', country: 'Barbados', type: 'country', region: 'north-america' },
  // Cities
  { name: 'New York, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Los Angeles, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'San Francisco, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Chicago, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Miami, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Las Vegas, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'New Orleans, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Washington DC, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Boston, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Seattle, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Austin, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Nashville, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Honolulu, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'San Diego, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Denver, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Portland, USA', country: 'United States', type: 'city', region: 'north-america' },
  { name: 'Toronto, Canada', country: 'Canada', type: 'city', region: 'north-america' },
  { name: 'Vancouver, Canada', country: 'Canada', type: 'city', region: 'north-america' },
  { name: 'Montreal, Canada', country: 'Canada', type: 'city', region: 'north-america' },
  { name: 'Quebec City, Canada', country: 'Canada', type: 'city', region: 'north-america' },
  { name: 'Banff, Canada', country: 'Canada', type: 'city', region: 'north-america' },
  { name: 'Calgary, Canada', country: 'Canada', type: 'city', region: 'north-america' },
  { name: 'Mexico City, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'Cancun, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'Playa del Carmen, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'Oaxaca, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'Tulum, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'Guadalajara, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'Puerto Vallarta, Mexico', country: 'Mexico', type: 'city', region: 'north-america' },
  { name: 'San Jose, Costa Rica', country: 'Costa Rica', type: 'city', region: 'north-america' },
  { name: 'Monteverde, Costa Rica', country: 'Costa Rica', type: 'city', region: 'north-america' },
  { name: 'Panama City, Panama', country: 'Panama', type: 'city', region: 'north-america' },
  { name: 'Antigua Guatemala, Guatemala', country: 'Guatemala', type: 'city', region: 'north-america' },
  { name: 'Havana, Cuba', country: 'Cuba', type: 'city', region: 'north-america' },
  { name: 'Kingston, Jamaica', country: 'Jamaica', type: 'city', region: 'north-america' },
  { name: 'Punta Cana, Dominican Republic', country: 'Dominican Republic', type: 'city', region: 'north-america' },
  { name: 'San Juan, Puerto Rico', country: 'Puerto Rico', type: 'city', region: 'north-america' },

  // ============ SOUTH AMERICA ============
  // Countries
  { name: 'Brazil', country: 'Brazil', type: 'country', region: 'south-america' },
  { name: 'Argentina', country: 'Argentina', type: 'country', region: 'south-america' },
  { name: 'Colombia', country: 'Colombia', type: 'country', region: 'south-america' },
  { name: 'Peru', country: 'Peru', type: 'country', region: 'south-america' },
  { name: 'Chile', country: 'Chile', type: 'country', region: 'south-america' },
  { name: 'Ecuador', country: 'Ecuador', type: 'country', region: 'south-america' },
  { name: 'Bolivia', country: 'Bolivia', type: 'country', region: 'south-america' },
  { name: 'Uruguay', country: 'Uruguay', type: 'country', region: 'south-america' },
  { name: 'Paraguay', country: 'Paraguay', type: 'country', region: 'south-america' },
  { name: 'Venezuela', country: 'Venezuela', type: 'country', region: 'south-america' },
  { name: 'Guyana', country: 'Guyana', type: 'country', region: 'south-america' },
  { name: 'Suriname', country: 'Suriname', type: 'country', region: 'south-america' },
  // Cities
  { name: 'Rio de Janeiro, Brazil', country: 'Brazil', type: 'city', region: 'south-america' },
  { name: 'Sao Paulo, Brazil', country: 'Brazil', type: 'city', region: 'south-america' },
  { name: 'Salvador, Brazil', country: 'Brazil', type: 'city', region: 'south-america' },
  { name: 'Florianopolis, Brazil', country: 'Brazil', type: 'city', region: 'south-america' },
  { name: 'Buenos Aires, Argentina', country: 'Argentina', type: 'city', region: 'south-america' },
  { name: 'Mendoza, Argentina', country: 'Argentina', type: 'city', region: 'south-america' },
  { name: 'Patagonia, Argentina', country: 'Argentina', type: 'city', region: 'south-america' },
  { name: 'Bariloche, Argentina', country: 'Argentina', type: 'city', region: 'south-america' },
  { name: 'Bogota, Colombia', country: 'Colombia', type: 'city', region: 'south-america' },
  { name: 'Medellin, Colombia', country: 'Colombia', type: 'city', region: 'south-america' },
  { name: 'Cartagena, Colombia', country: 'Colombia', type: 'city', region: 'south-america' },
  { name: 'Cali, Colombia', country: 'Colombia', type: 'city', region: 'south-america' },
  { name: 'Lima, Peru', country: 'Peru', type: 'city', region: 'south-america' },
  { name: 'Cusco, Peru', country: 'Peru', type: 'city', region: 'south-america' },
  { name: 'Machu Picchu, Peru', country: 'Peru', type: 'city', region: 'south-america' },
  { name: 'Santiago, Chile', country: 'Chile', type: 'city', region: 'south-america' },
  { name: 'Valparaiso, Chile', country: 'Chile', type: 'city', region: 'south-america' },
  { name: 'Atacama Desert, Chile', country: 'Chile', type: 'city', region: 'south-america' },
  { name: 'Quito, Ecuador', country: 'Ecuador', type: 'city', region: 'south-america' },
  { name: 'Galapagos Islands, Ecuador', country: 'Ecuador', type: 'city', region: 'south-america' },
  { name: 'La Paz, Bolivia', country: 'Bolivia', type: 'city', region: 'south-america' },
  { name: 'Uyuni Salt Flats, Bolivia', country: 'Bolivia', type: 'city', region: 'south-america' },
  { name: 'Montevideo, Uruguay', country: 'Uruguay', type: 'city', region: 'south-america' },

  // ============ AFRICA ============
  // Countries
  { name: 'Morocco', country: 'Morocco', type: 'country', region: 'africa' },
  { name: 'Egypt', country: 'Egypt', type: 'country', region: 'africa' },
  { name: 'South Africa', country: 'South Africa', type: 'country', region: 'africa' },
  { name: 'Kenya', country: 'Kenya', type: 'country', region: 'africa' },
  { name: 'Tanzania', country: 'Tanzania', type: 'country', region: 'africa' },
  { name: 'Ethiopia', country: 'Ethiopia', type: 'country', region: 'africa' },
  { name: 'Ghana', country: 'Ghana', type: 'country', region: 'africa' },
  { name: 'Nigeria', country: 'Nigeria', type: 'country', region: 'africa' },
  { name: 'Senegal', country: 'Senegal', type: 'country', region: 'africa' },
  { name: 'Tunisia', country: 'Tunisia', type: 'country', region: 'africa' },
  { name: 'Rwanda', country: 'Rwanda', type: 'country', region: 'africa' },
  { name: 'Uganda', country: 'Uganda', type: 'country', region: 'africa' },
  { name: 'Madagascar', country: 'Madagascar', type: 'country', region: 'africa' },
  { name: 'Namibia', country: 'Namibia', type: 'country', region: 'africa' },
  { name: 'Botswana', country: 'Botswana', type: 'country', region: 'africa' },
  { name: 'Zimbabwe', country: 'Zimbabwe', type: 'country', region: 'africa' },
  { name: 'Mozambique', country: 'Mozambique', type: 'country', region: 'africa' },
  { name: 'Zambia', country: 'Zambia', type: 'country', region: 'africa' },
  { name: 'Mauritius', country: 'Mauritius', type: 'country', region: 'africa' },
  { name: 'Seychelles', country: 'Seychelles', type: 'country', region: 'africa' },
  { name: 'Algeria', country: 'Algeria', type: 'country', region: 'africa' },
  { name: 'Ivory Coast', country: 'Ivory Coast', type: 'country', region: 'africa' },
  { name: 'Cameroon', country: 'Cameroon', type: 'country', region: 'africa' },
  // Cities
  { name: 'Marrakech, Morocco', country: 'Morocco', type: 'city', region: 'africa' },
  { name: 'Fes, Morocco', country: 'Morocco', type: 'city', region: 'africa' },
  { name: 'Casablanca, Morocco', country: 'Morocco', type: 'city', region: 'africa' },
  { name: 'Chefchaouen, Morocco', country: 'Morocco', type: 'city', region: 'africa' },
  { name: 'Cairo, Egypt', country: 'Egypt', type: 'city', region: 'africa' },
  { name: 'Luxor, Egypt', country: 'Egypt', type: 'city', region: 'africa' },
  { name: 'Hurghada, Egypt', country: 'Egypt', type: 'city', region: 'africa' },
  { name: 'Cape Town, South Africa', country: 'South Africa', type: 'city', region: 'africa' },
  { name: 'Johannesburg, South Africa', country: 'South Africa', type: 'city', region: 'africa' },
  { name: 'Durban, South Africa', country: 'South Africa', type: 'city', region: 'africa' },
  { name: 'Kruger National Park, South Africa', country: 'South Africa', type: 'city', region: 'africa' },
  { name: 'Nairobi, Kenya', country: 'Kenya', type: 'city', region: 'africa' },
  { name: 'Masai Mara, Kenya', country: 'Kenya', type: 'city', region: 'africa' },
  { name: 'Mombasa, Kenya', country: 'Kenya', type: 'city', region: 'africa' },
  { name: 'Zanzibar, Tanzania', country: 'Tanzania', type: 'city', region: 'africa' },
  { name: 'Dar es Salaam, Tanzania', country: 'Tanzania', type: 'city', region: 'africa' },
  { name: 'Serengeti, Tanzania', country: 'Tanzania', type: 'city', region: 'africa' },
  { name: 'Addis Ababa, Ethiopia', country: 'Ethiopia', type: 'city', region: 'africa' },
  { name: 'Accra, Ghana', country: 'Ghana', type: 'city', region: 'africa' },
  { name: 'Lagos, Nigeria', country: 'Nigeria', type: 'city', region: 'africa' },
  { name: 'Dakar, Senegal', country: 'Senegal', type: 'city', region: 'africa' },
  { name: 'Tunis, Tunisia', country: 'Tunisia', type: 'city', region: 'africa' },
  { name: 'Kigali, Rwanda', country: 'Rwanda', type: 'city', region: 'africa' },
  { name: 'Kampala, Uganda', country: 'Uganda', type: 'city', region: 'africa' },
  { name: 'Windhoek, Namibia', country: 'Namibia', type: 'city', region: 'africa' },
  { name: 'Victoria Falls, Zimbabwe', country: 'Zimbabwe', type: 'city', region: 'africa' },
  { name: 'Antananarivo, Madagascar', country: 'Madagascar', type: 'city', region: 'africa' },

  // ============ SOUTH & EAST ASIA ============
  // Countries
  { name: 'Japan', country: 'Japan', type: 'country', region: 'south-east-asia' },
  { name: 'Thailand', country: 'Thailand', type: 'country', region: 'south-east-asia' },
  { name: 'Vietnam', country: 'Vietnam', type: 'country', region: 'south-east-asia' },
  { name: 'Indonesia', country: 'Indonesia', type: 'country', region: 'south-east-asia' },
  { name: 'Philippines', country: 'Philippines', type: 'country', region: 'south-east-asia' },
  { name: 'South Korea', country: 'South Korea', type: 'country', region: 'south-east-asia' },
  { name: 'China', country: 'China', type: 'country', region: 'south-east-asia' },
  { name: 'Taiwan', country: 'Taiwan', type: 'country', region: 'south-east-asia' },
  { name: 'Malaysia', country: 'Malaysia', type: 'country', region: 'south-east-asia' },
  { name: 'Singapore', country: 'Singapore', type: 'country', region: 'south-east-asia' },
  { name: 'Cambodia', country: 'Cambodia', type: 'country', region: 'south-east-asia' },
  { name: 'Myanmar', country: 'Myanmar', type: 'country', region: 'south-east-asia' },
  { name: 'Laos', country: 'Laos', type: 'country', region: 'south-east-asia' },
  { name: 'Mongolia', country: 'Mongolia', type: 'country', region: 'south-east-asia' },
  // Cities
  { name: 'Tokyo, Japan', country: 'Japan', type: 'city', region: 'south-east-asia' },
  { name: 'Kyoto, Japan', country: 'Japan', type: 'city', region: 'south-east-asia' },
  { name: 'Osaka, Japan', country: 'Japan', type: 'city', region: 'south-east-asia' },
  { name: 'Hiroshima, Japan', country: 'Japan', type: 'city', region: 'south-east-asia' },
  { name: 'Nara, Japan', country: 'Japan', type: 'city', region: 'south-east-asia' },
  { name: 'Bangkok, Thailand', country: 'Thailand', type: 'city', region: 'south-east-asia' },
  { name: 'Chiang Mai, Thailand', country: 'Thailand', type: 'city', region: 'south-east-asia' },
  { name: 'Phuket, Thailand', country: 'Thailand', type: 'city', region: 'south-east-asia' },
  { name: 'Krabi, Thailand', country: 'Thailand', type: 'city', region: 'south-east-asia' },
  { name: 'Koh Samui, Thailand', country: 'Thailand', type: 'city', region: 'south-east-asia' },
  { name: 'Hanoi, Vietnam', country: 'Vietnam', type: 'city', region: 'south-east-asia' },
  { name: 'Ho Chi Minh City, Vietnam', country: 'Vietnam', type: 'city', region: 'south-east-asia' },
  { name: 'Da Nang, Vietnam', country: 'Vietnam', type: 'city', region: 'south-east-asia' },
  { name: 'Hoi An, Vietnam', country: 'Vietnam', type: 'city', region: 'south-east-asia' },
  { name: 'Ha Long Bay, Vietnam', country: 'Vietnam', type: 'city', region: 'south-east-asia' },
  { name: 'Bali, Indonesia', country: 'Indonesia', type: 'city', region: 'south-east-asia' },
  { name: 'Jakarta, Indonesia', country: 'Indonesia', type: 'city', region: 'south-east-asia' },
  { name: 'Yogyakarta, Indonesia', country: 'Indonesia', type: 'city', region: 'south-east-asia' },
  { name: 'Lombok, Indonesia', country: 'Indonesia', type: 'city', region: 'south-east-asia' },
  { name: 'Manila, Philippines', country: 'Philippines', type: 'city', region: 'south-east-asia' },
  { name: 'Palawan, Philippines', country: 'Philippines', type: 'city', region: 'south-east-asia' },
  { name: 'Cebu, Philippines', country: 'Philippines', type: 'city', region: 'south-east-asia' },
  { name: 'Boracay, Philippines', country: 'Philippines', type: 'city', region: 'south-east-asia' },
  { name: 'Seoul, South Korea', country: 'South Korea', type: 'city', region: 'south-east-asia' },
  { name: 'Busan, South Korea', country: 'South Korea', type: 'city', region: 'south-east-asia' },
  { name: 'Jeju Island, South Korea', country: 'South Korea', type: 'city', region: 'south-east-asia' },
  { name: 'Beijing, China', country: 'China', type: 'city', region: 'south-east-asia' },
  { name: 'Shanghai, China', country: 'China', type: 'city', region: 'south-east-asia' },
  { name: 'Hong Kong', country: 'China', type: 'city', region: 'south-east-asia' },
  { name: 'Taipei, Taiwan', country: 'Taiwan', type: 'city', region: 'south-east-asia' },
  { name: 'Kuala Lumpur, Malaysia', country: 'Malaysia', type: 'city', region: 'south-east-asia' },
  { name: 'Penang, Malaysia', country: 'Malaysia', type: 'city', region: 'south-east-asia' },
  { name: 'Langkawi, Malaysia', country: 'Malaysia', type: 'city', region: 'south-east-asia' },
  { name: 'Singapore', country: 'Singapore', type: 'city', region: 'south-east-asia' },
  { name: 'Siem Reap, Cambodia', country: 'Cambodia', type: 'city', region: 'south-east-asia' },
  { name: 'Phnom Penh, Cambodia', country: 'Cambodia', type: 'city', region: 'south-east-asia' },
  { name: 'Luang Prabang, Laos', country: 'Laos', type: 'city', region: 'south-east-asia' },
  { name: 'Ulaanbaatar, Mongolia', country: 'Mongolia', type: 'city', region: 'south-east-asia' },

  // ============ NORTH & CENTRAL ASIA (Middle East + South Asia) ============
  // Countries
  { name: 'Turkey', country: 'Turkey', type: 'country', region: 'north-central-asia' },
  { name: 'India', country: 'India', type: 'country', region: 'north-central-asia' },
  { name: 'UAE', country: 'UAE', type: 'country', region: 'north-central-asia' },
  { name: 'Israel', country: 'Israel', type: 'country', region: 'north-central-asia' },
  { name: 'Jordan', country: 'Jordan', type: 'country', region: 'north-central-asia' },
  { name: 'Oman', country: 'Oman', type: 'country', region: 'north-central-asia' },
  { name: 'Saudi Arabia', country: 'Saudi Arabia', type: 'country', region: 'north-central-asia' },
  { name: 'Qatar', country: 'Qatar', type: 'country', region: 'north-central-asia' },
  { name: 'Sri Lanka', country: 'Sri Lanka', type: 'country', region: 'north-central-asia' },
  { name: 'Nepal', country: 'Nepal', type: 'country', region: 'north-central-asia' },
  { name: 'Georgia', country: 'Georgia', type: 'country', region: 'north-central-asia' },
  { name: 'Armenia', country: 'Armenia', type: 'country', region: 'north-central-asia' },
  { name: 'Azerbaijan', country: 'Azerbaijan', type: 'country', region: 'north-central-asia' },
  { name: 'Uzbekistan', country: 'Uzbekistan', type: 'country', region: 'north-central-asia' },
  { name: 'Kazakhstan', country: 'Kazakhstan', type: 'country', region: 'north-central-asia' },
  { name: 'Pakistan', country: 'Pakistan', type: 'country', region: 'north-central-asia' },
  { name: 'Bangladesh', country: 'Bangladesh', type: 'country', region: 'north-central-asia' },
  { name: 'Maldives', country: 'Maldives', type: 'country', region: 'north-central-asia' },
  { name: 'Bhutan', country: 'Bhutan', type: 'country', region: 'north-central-asia' },
  { name: 'Iran', country: 'Iran', type: 'country', region: 'north-central-asia' },
  { name: 'Lebanon', country: 'Lebanon', type: 'country', region: 'north-central-asia' },
  { name: 'Russia', country: 'Russia', type: 'country', region: 'north-central-asia' },
  // Cities
  { name: 'Istanbul, Turkey', country: 'Turkey', type: 'city', region: 'north-central-asia' },
  { name: 'Cappadocia, Turkey', country: 'Turkey', type: 'city', region: 'north-central-asia' },
  { name: 'Antalya, Turkey', country: 'Turkey', type: 'city', region: 'north-central-asia' },
  { name: 'Bodrum, Turkey', country: 'Turkey', type: 'city', region: 'north-central-asia' },
  { name: 'Dubai, UAE', country: 'UAE', type: 'city', region: 'north-central-asia' },
  { name: 'Abu Dhabi, UAE', country: 'UAE', type: 'city', region: 'north-central-asia' },
  { name: 'Delhi, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Mumbai, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Jaipur, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Goa, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Varanasi, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Agra, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Kerala, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Udaipur, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Bangalore, India', country: 'India', type: 'city', region: 'north-central-asia' },
  { name: 'Tel Aviv, Israel', country: 'Israel', type: 'city', region: 'north-central-asia' },
  { name: 'Jerusalem, Israel', country: 'Israel', type: 'city', region: 'north-central-asia' },
  { name: 'Amman, Jordan', country: 'Jordan', type: 'city', region: 'north-central-asia' },
  { name: 'Petra, Jordan', country: 'Jordan', type: 'city', region: 'north-central-asia' },
  { name: 'Dead Sea, Jordan', country: 'Jordan', type: 'city', region: 'north-central-asia' },
  { name: 'Muscat, Oman', country: 'Oman', type: 'city', region: 'north-central-asia' },
  { name: 'Doha, Qatar', country: 'Qatar', type: 'city', region: 'north-central-asia' },
  { name: 'Riyadh, Saudi Arabia', country: 'Saudi Arabia', type: 'city', region: 'north-central-asia' },
  { name: 'Colombo, Sri Lanka', country: 'Sri Lanka', type: 'city', region: 'north-central-asia' },
  { name: 'Ella, Sri Lanka', country: 'Sri Lanka', type: 'city', region: 'north-central-asia' },
  { name: 'Kathmandu, Nepal', country: 'Nepal', type: 'city', region: 'north-central-asia' },
  { name: 'Pokhara, Nepal', country: 'Nepal', type: 'city', region: 'north-central-asia' },
  { name: 'Tbilisi, Georgia', country: 'Georgia', type: 'city', region: 'north-central-asia' },
  { name: 'Yerevan, Armenia', country: 'Armenia', type: 'city', region: 'north-central-asia' },
  { name: 'Baku, Azerbaijan', country: 'Azerbaijan', type: 'city', region: 'north-central-asia' },
  { name: 'Samarkand, Uzbekistan', country: 'Uzbekistan', type: 'city', region: 'north-central-asia' },
  { name: 'Tashkent, Uzbekistan', country: 'Uzbekistan', type: 'city', region: 'north-central-asia' },
  { name: 'Male, Maldives', country: 'Maldives', type: 'city', region: 'north-central-asia' },
  { name: 'Thimphu, Bhutan', country: 'Bhutan', type: 'city', region: 'north-central-asia' },
  { name: 'Beirut, Lebanon', country: 'Lebanon', type: 'city', region: 'north-central-asia' },
  { name: 'Moscow, Russia', country: 'Russia', type: 'city', region: 'north-central-asia' },
  { name: 'St. Petersburg, Russia', country: 'Russia', type: 'city', region: 'north-central-asia' },

  // ============ OCEANIA ============
  // Countries
  { name: 'Australia', country: 'Australia', type: 'country', region: 'oceania' },
  { name: 'New Zealand', country: 'New Zealand', type: 'country', region: 'oceania' },
  { name: 'Fiji', country: 'Fiji', type: 'country', region: 'oceania' },
  { name: 'French Polynesia', country: 'French Polynesia', type: 'country', region: 'oceania' },
  { name: 'Samoa', country: 'Samoa', type: 'country', region: 'oceania' },
  { name: 'Tonga', country: 'Tonga', type: 'country', region: 'oceania' },
  { name: 'Vanuatu', country: 'Vanuatu', type: 'country', region: 'oceania' },
  { name: 'Papua New Guinea', country: 'Papua New Guinea', type: 'country', region: 'oceania' },
  { name: 'New Caledonia', country: 'New Caledonia', type: 'country', region: 'oceania' },
  // Cities
  { name: 'Sydney, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Melbourne, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Brisbane, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Perth, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Gold Coast, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Cairns, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Great Barrier Reef, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Adelaide, Australia', country: 'Australia', type: 'city', region: 'oceania' },
  { name: 'Auckland, New Zealand', country: 'New Zealand', type: 'city', region: 'oceania' },
  { name: 'Queenstown, New Zealand', country: 'New Zealand', type: 'city', region: 'oceania' },
  { name: 'Wellington, New Zealand', country: 'New Zealand', type: 'city', region: 'oceania' },
  { name: 'Rotorua, New Zealand', country: 'New Zealand', type: 'city', region: 'oceania' },
  { name: 'Milford Sound, New Zealand', country: 'New Zealand', type: 'city', region: 'oceania' },
  { name: 'Nadi, Fiji', country: 'Fiji', type: 'city', region: 'oceania' },
  { name: 'Bora Bora, French Polynesia', country: 'French Polynesia', type: 'city', region: 'oceania' },
  { name: 'Tahiti, French Polynesia', country: 'French Polynesia', type: 'city', region: 'oceania' },
];
